categoryBar:
  enable: true
  column: odd # 显示列数,odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  descr:
    - 学习使我快乐
    - 杂谈测评
    - 一些个人项目
  cover:
    - url('https://s.pc.qq.com/tousu/img/20211003/5532881_1633240792.jpg')
    - url('https://s.pc.qq.com/tousu/img/20211003/8502201_1633240839.jpg')
    - url('https://s.pc.qq.com/tousu/img/20211003/8475850_1633240877.jpg')

    # Loading Animation (加載動畫)
  preloader:
     enable: true # true|false
     load_color: '#000000' # '#37474f'
     load_style: ironheart # # spinner-box|wizard|ironheart|scarecrow|image
     load_image:  # url